/**
 * Server-local re-export of the wire protocol. The canonical definition lives in @maple/shared/net
 * so the browser client and this server share one source of truth without bundling server code.
 */
export {
  MessageType,
  type InputData,
  type ChatPayload,
  type ChatMessage,
  type MessageTypeValue,
  type CreateCharacterPayload,
  type DeleteCharacterPayload,
  type TravelPayload,
  type SessionGenerationPayload,
  type ForceLogoutPayload,
  type FerryBlockedPayload,
  type TalkNpcPayload,
  type DialogLinePayload,
  type DialogChoicePayload,
  type DialogEndPayload,
  type JobAdvancePayload,
  type BranchListPayload,
  type BranchChoicePayload,
  type QuestUpdatePayload,
  type QuestOfferPayload,
  type QuestAcceptPayload,
  type QuestDeclinePayload,
  type QuestTurninOfferPayload,
  type QuestTurninAcceptPayload,
  type QuestTurninDeclinePayload,
  type QuestObjectiveInfo,
  type BuyCashItemPayload,
  type BuyCashItemResultPayload,
  type EquipCashItemPayload,
  type EquipCashItemResultPayload,
  type CashInfoRequestPayload,
  type CashInfoPayload,
  type EquipItemPayload,
  type UnequipItemPayload,
  type BuyFromShopPayload,
  type BuyFromShopResultPayload,
  type SellToShopPayload,
  type SellToShopResultPayload,
  type SpendApPayload,
  type LearnSkillPayload,
  type LearnSkillResultPayload,
  type SkillBookRequestPayload,
  type SkillBookResponsePayload,
  type LevelUpPayload,
  type CombatHitPayload,
  type StatusEffectsPayload,
  type TradeInvitePayload,
  type TradeAcceptPayload,
  type TradeRejectPayload,
  type TradeCancelPayload,
  type TradeOfferPayload,
  type TradeLockPayload,
  type TradeConfirmPayload,
  type TradeUpdatePayload,
  type TradeResultPayload,
  type MarketListPayload,
  type MarketCancelPayload,
  type MarketBrowsePayload,
  type MarketBuyPayload,
  type MarketResultPayload,
  type MarketBrowseResultPayload,
  type MarketErrorPayload,
  type StorageDepositPayload,
  type StorageWithdrawPayload,
  type StorageSyncPayload,
  type StorageResultPayload,
  type RepairEquipmentPayload,
  type RepairResultPayload,
  type CubeRerollPayload,
  type CubeRerollResultPayload,
  type UpgradeItemPayload,
  type UpgradeItemResultPayload,
  type StarForcePayload,
  type StarForceResultPayload,
  type PartyInvitePayload,
  type PartyInviteReceivedPayload,
  type PartyAcceptPayload,
  type PartyLeavePayload,
  type PartyKickPayload,
  type PartyMemberSnapshot,
  type PartyUpdatePayload,
  type GuildRank,
  type GuildMember,
  type GuildUpdatePayload,
  type GuildCreatePayload,
  type GuildInvitePayload,
  type GuildInviteReceivedPayload,
  type GuildAcceptPayload,
  type GuildLeavePayload,
  type GuildKickPayload,
  type GuildRankPayload,
  type GuildChatPayload,
  type GuildChatRelayPayload,
  type GuildResultPayload,
  type ChannelInfo,
  type ChannelListPayload,
  type ChannelSwitchPayload,
  type ChannelSwitchResultPayload,
  type WhisperPayload,
  type WhisperRelayPayload,
  type WhisperFailedPayload,
  type GiveFamePayload,
  type FameResultPayload,
  type CodexSyncPayload,
  type ViewCodexPayload,
  type AchievementSyncPayload,
  type AchievementUnlockPayload,
  type ViewAchievementsPayload,
  type PQJoinPayload,
  type PQProgressPayload,
  type PQResultPayload,
  type PQContributePayload,
  type PQStageSnapshot,
  type SkillCastPayload,
  type SkillCastResultPayload,
  type UseConsumablePayload,
  type UseConsumableResultPayload,
  type QuickSlotLayoutPayload,
  type SettingsPayload,
  type FeedbackCategory,
  type FeedbackSubmitPayload,
  type FeedbackResultPayload,
  type PlayerReportPayload,
  type PlayerReportResultPayload,
  type BlockPlayerPayload,
  type UnblockPlayerPayload,
  type BlockedListResultPayload,
  type ServerAnnouncementPayload,
  type ModActionResultPayload,
  // ─── Party chat ──────────────────────────────────────────────────────────
  type PartyChatPayload,
  type PartyChatRelayPayload,
  type ChatScope,

  // ─── Party loot rule ────────────────────────────────────────────────────
  type LootRule,
  type PartySetLootRulePayload,

  // ─── LFG / Party Finder ─────────────────────────────────────────────────
  type LfgPostPayload,
  type LfgListingSnapshot,
  type LfgListResultPayload,
  type LfgJoinPayload,
  type LfgRemovePayload,

  // ─── Guided progression (Maple Guide) ────────────────────────────────────
  type GuidanceSyncPayload,
  type GuideTravelPayload,

  // ─── World map quick-travel ─────────────────────────────────────────────
  type MapTravelPayload,

  // ─── Bonus Hunting (rotating daily map) ───────────────────────────────────
  type BonusHuntSyncPayload,

  // ─── Friends / Buddy list ─────────────────────────────────────────────────
  type FriendEntry,
  type FriendAddPayload,
  type FriendRemovePayload,
  type FriendListPayload,
  type FriendResultPayload,
  type FriendRemovedPayload,
  type OnlineStatusPayload,

  // ─── Flame (bonus stat reroll) ──────────────────────────────────────
  type FlameRerollPayload,
  type FlameRerollResultPayload,

  // ─── Familiar system ─────────────────────────────────────────────────
  type FamiliarSyncPayload,
  type FamiliarSummonPayload,
  type FamiliarDismissPayload,
  type FamiliarCardDropPayload,

  // ─── Runes ───────────────────────────────────────────────────────────────
  type RuneSpawnPayload,
  type RuneDespawnPayload,
  type RuneActivatePayload,
  type RuneType,

  // ─── Treasure Hunter Boxes ────────────────────────────────────────────────
  type TreasureSpawnPayload,
  type TreasureHitPayload,
  type TreasureDestroyPayload,

  // ─── Exploration Dispatch ─────────────────────────────────────────────
  type ExplorationStartPayload,
  type ExplorationClaimPayload,
  type ExplorationSyncPayload,
  type ExplorationStartResultPayload,
  type ExplorationClaimResultPayload,

  // ─── Titles ──────────────────────────────────────────────────────────────
  type EquipTitlePayload,
  type TitleSyncPayload,
} from "@maple/shared";
